version: '3.8'
# Version of the Docker Compose file format
services: #list all the different parts of the application
  web: # the web application
    build: . # build the Dockerfile in the current directory
    ports: # expose the web application on port 5002
      - "5003:5003" 
    depends_on:
      - redis # the web application depends on the database service
      
  redis: # the database service
    image: "redis:latest"
    ports:
     - "6379:6379"